version: '3'
services:
  ngrok_telegram:
    container_name: ngrok_telegram.srg
    image: wernight/ngrok
    environment:
      - NGROK_AUTH=${NGROK_AUTH}
      - NGROK_PORT=${NGROK_PORT}
    ports:
      - "4040:4040"
    networks:
      - sarge.local
  sarge:
    build:
      context: ./sarge_src
      dockerfile: Dockerfile
    container_name: sarge.srg
    volumes:
      - "./sarge_src:/app"
    depends_on:
      - ngrok_telegram
    environment:
      - NGROK_CONTAINER=ngrok_telegram
      - SERVER_PORT=3000
      - APP_ENV=${APP_ENV}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    networks:
      - sarge.local
    volumes:
      - ./downloads:/down
      - ./sarge_src:/app
networks:
  sarge.local:
    driver: bridge
  

